config/routes.rb
Rails.application.routes.draw do
  resources :cepas
  resources :vinos
  resources :vino_cepas  

  root 'vinos#index'

  put 'vino_cepas/:id/add_porcentaje', to: 'vino_cepas#add_porcentaje', as: 'vc_add_porcentaje'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cepa.rb
class Cepa < ApplicationRecord
    has_many :vino_cepas
    has_many :vinos, through: :vino_cepas
end

app/models/vino.rb
class Vino < ApplicationRecord
    has_many :vino_cepas
    has_many :cepas, through: :vino_cepas
end

app/models/vino_cepa.rb
class VinoCepa < ApplicationRecord
    belongs_to :vino
    belongs_to :cepa
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cepas_controller.rb
class CepasController < ApplicationController
  before_action :set_cepa, only: %i[ show edit update destroy ]

  # GET /cepas or /cepas.json
  def index
    @cepas = Cepa.all
  end

  # GET /cepas/1 or /cepas/1.json
  def show
  end

  # GET /cepas/new
  def new
    @cepa = Cepa.new
  end

  # GET /cepas/1/edit
  def edit
  end

  # POST /cepas or /cepas.json
  def create
    @cepa = Cepa.new(cepa_params)

    respond_to do |format|
      if @cepa.save
        format.html { redirect_to cepa_url(@cepa), notice: "Cepa was successfully created." }
        format.json { render :show, status: :created, location: @cepa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cepa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cepas/1 or /cepas/1.json
  def update
    respond_to do |format|
      if @cepa.update(cepa_params)
        format.html { redirect_to cepa_url(@cepa), notice: "Cepa was successfully updated." }
        format.json { render :show, status: :ok, location: @cepa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cepa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cepas/1 or /cepas/1.json
  def destroy
    @cepa.destroy

    respond_to do |format|
      format.html { redirect_to cepas_url, notice: "Cepa was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cepa
      @cepa = Cepa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cepa_params
      params.require(:cepa).permit(:name)
    end
end

app/controllers/vino_cepas_controller.rb
class VinoCepasController < ApplicationController
  before_action :set_vino_cepa, only: %i[ show edit update destroy ]

  # GET /vino_cepas or /vino_cepas.json
  def index
    @vino_cepas = VinoCepa.all
  end

  # GET /vino_cepas/1 or /vino_cepas/1.json
  def show
  end

  # GET /vino_cepas/new
  def new
    @vino_cepa = VinoCepa.new
  end

  # GET /vino_cepas/1/edit
  def edit
  end

  # POST /vino_cepas or /vino_cepas.json
  def create
    @vino_cepa = VinoCepa.new(vino_cepa_params)

    respond_to do |format|
      if @vino_cepa.save
        format.html { redirect_to vino_cepa_url(@vino_cepa), notice: "Vino cepa was successfully created." }
        format.json { render :show, status: :created, location: @vino_cepa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vino_cepa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vino_cepas/1 or /vino_cepas/1.json
  def update
    respond_to do |format|
      if @vino_cepa.update(vino_cepa_params)
        format.html { redirect_to vino_cepa_url(@vino_cepa), notice: "Vino cepa was successfully updated." }
        format.json { render :show, status: :ok, location: @vino_cepa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vino_cepa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vino_cepas/1 or /vino_cepas/1.json
  def destroy
    @vino_cepa.destroy

    respond_to do |format|
      format.html { redirect_to vino_cepas_url, notice: "Vino cepa was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_porcentaje
    vc = VinoCepa.find(params[:id])

    vc.porcentaje = params[:porcentaje]
    if vc.save
      flash[:success] = "Guardado"
    else
      flash[:danger] = "Error"
    end
    redirect_to vc.vino
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vino_cepa
      @vino_cepa = VinoCepa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vino_cepa_params
      params.fetch(:vino_cepa, {})
    end
end

app/controllers/vinos_controller.rb
class VinosController < ApplicationController
  before_action :set_vino, only: %i[ show edit update destroy ]

  # GET /vinos or /vinos.json
  def index
    @vinos = Vino.all
  end

  # GET /vinos/1 or /vinos/1.json
  def show
  end

  # GET /vinos/new
  def new
    @vino = Vino.new
  end

  # GET /vinos/1/edit
  def edit
  end

  # POST /vinos or /vinos.json
  def create
    @vino = Vino.new(vino_params)

    respond_to do |format|
      if @vino.save
        format.html { redirect_to vino_url(@vino), notice: "Vino was successfully created." }
        format.json { render :show, status: :created, location: @vino }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vino.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vinos/1 or /vinos/1.json
  def update
    respond_to do |format|
      if @vino.update(vino_params)
        format.html { redirect_to vino_url(@vino), notice: "Vino was successfully updated." }
        format.json { render :show, status: :ok, location: @vino }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vino.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vinos/1 or /vinos/1.json
  def destroy
    @vino.destroy

    respond_to do |format|
      format.html { redirect_to vinos_url, notice: "Vino was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vino
      @vino = Vino.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vino_params
      params.require(:vino).permit(:name, {cepa_ids: []})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cepas_helper.rb
module CepasHelper
end

app/helpers/vino_cepas_helper.rb
module VinoCepasHelper
end

app/helpers/vinos_helper.rb
module VinosHelper
end

app/views/cepas/_form.html.erb
<%= form_with(model: cepa) do |form| %>
  <% if cepa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cepa.errors.count, "error") %> prohibited this cepa from being saved:</h2>

      <ul>
        <% cepa.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cepas/edit.html.erb
<h1>Editing Cepa</h1>

<%= render 'form', cepa: @cepa %>

<%= link_to 'Show', @cepa %> |
<%= link_to 'Back', cepas_path %>

app/views/cepas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cepas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cepas.each do |cepa| %>
      <tr>
        <td><%= cepa.name %></td>
        <td><%= link_to 'Show', cepa %></td>
        <td><%= link_to 'Edit', edit_cepa_path(cepa) %></td>
        <td><%= link_to 'Destroy', cepa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cepa', new_cepa_path %>

app/views/cepas/new.html.erb
<h1>New Cepa</h1>

<%= render 'form', cepa: @cepa %>

<%= link_to 'Back', cepas_path %>

app/views/cepas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cepa.name %>
</p>

<%= link_to 'Edit', edit_cepa_path(@cepa) %> |
<%= link_to 'Back', cepas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cepas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vino_cepas/_form.html.erb
<%= form_with(model: vino_cepa) do |form| %>
  <% if vino_cepa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vino_cepa.errors.count, "error") %> prohibited this vino_cepa from being saved:</h2>

      <ul>
        <% vino_cepa.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vino_cepas/edit.html.erb
<h1>Editing Vino Cepa</h1>

<%= render 'form', vino_cepa: @vino_cepa %>

<%= link_to 'Show', @vino_cepa %> |
<%= link_to 'Back', vino_cepas_path %>

app/views/vino_cepas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vino Cepas</h1>

<table>
  <thead>
    <tr>
      <th>Vino</th>
      <th>Cepa</th>
      <th>Disponible</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vino_cepas.each do |vino_cepa| %>
      <tr>
        <td><%= vino_cepa.vino.name%></td>
        <td><%= vino_cepa.cepa.name%></td>
        <td><%= vino_cepa.available%></td>
        <td><%= link_to 'Show', vino_cepa %></td>
        <td><%= link_to 'Edit', edit_vino_cepa_path(vino_cepa) %></td>
        <td><%= link_to 'Destroy', vino_cepa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vino Cepa', new_vino_cepa_path %>

app/views/vino_cepas/new.html.erb
<h1>New Vino Cepa</h1>

<%= render 'form', vino_cepa: @vino_cepa %>

<%= link_to 'Back', vino_cepas_path %>

app/views/vino_cepas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_vino_cepa_path(@vino_cepa) %> |
<%= link_to 'Back', vino_cepas_path %>

app/views/vinos/_form.html.erb
<%= form_with(model: vino) do |form| %>
  <% if vino.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vino.errors.count, "error") %> prohibited this vino from being saved:</h2>

      <ul>
        <% vino.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
  <%= form.label :cepas %>
    <%= form.collection_check_boxes(:cepa_ids, Cepa.all, :id, :name) do |b| %>
      <%= b.label class:"label-checkbox" do%>
      <%= b.check_box + b.text %>
    <%end%>
  <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vinos/_form_porcentaje.html.erb
<%= form_with(url: vc_add_porcentaje_path(vino_cepas), method: :put) do |f|%>
    <div class="field">
        <%= f.label'porcentaje', 'Porcentaje' %>
        <%= f.text_field 'porcentaje'%>
    </div>

    <div class="field">
        <%= f.submit 'Enviar'%>
    </div>
<% end %>

app/views/vinos/edit.html.erb
<h1>Editing Vino</h1>

<%= render 'form', vino: @vino %>

<%= link_to 'Show', @vino %> |
<%= link_to 'Back', vinos_path %>

app/views/vinos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vinos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Cepas</th>
      <th>Respectivos porcentajes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vinos.each do |vino| %>
      <tr>
        <td><%= vino.name %></td>
        <td><%= vino.cepas.map(&:name).join(', ') %></td>
        <td><%= vino.vino_cepas.map(&:porcentaje).join('%, ').concat('%') %></td>
        <td><%= link_to 'Show', vino %></td>
        <td><%= link_to 'Edit', edit_vino_path(vino) %></td>
        <td><%= link_to 'Destroy', vino, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Vino', new_vino_path %>

app/views/vinos/new.html.erb
<h1>New Vino</h1>

<%= render 'form', vino: @vino %>

<%= link_to 'Back', vinos_path %>

app/views/vinos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vino.name %>
</p>

<ul>
  <% @vino.vino_cepas.each do |vino_cepas| %>
    <li>
      <%= vino_cepas.cepa.name %>
      <% if vino_cepas.porcentaje.nil? %>
        <strong>Sin porcentaje de cepa</strong>
        <%= render partial: 'form_porcentaje', locals: {vino_cepas: vino_cepas} %>
      <% else %>
        <%= vino_cepas.porcentaje.to_s.concat("%") %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_vino_path(@vino) %> |
<%= link_to 'Back', vinos_path %>